Vagrant.configure("2") do |config|
  config.vm.define "ubuntu-24" do |srv|
    srv.vm.box = "bento/ubuntu-24.04"

    srv.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end

    srv.vm.disk :disk, size: "1GB", name: "disk1"
    srv.vm.disk :disk, size: "1GB", name: "disk2"

    srv.vm.network :forwarded_port,
                   guest: 80,
                   host: 8080,
                   host_ip: "127.0.0.1"


    # Provisioning - монтирование дисков
    srv.vm.provision "shell", inline: <<-SHELL
      # Форматирование дисков в ext4 (только если ещё не отформатированы)
      mkfs.ext4 -F /dev/sdb
      mkfs.ext4 -F /dev/sdc

      # Создание точек монтирования
      mkdir -p /mnt/disk1
      mkdir -p /mnt/disk2

      # Монтирование дисков
      mount /dev/sdb /mnt/disk1
      mount /dev/sdc /mnt/disk2

      # Добавление записей в /etc/fstab (если ещё не добавлены)
      echo "UUID=$(blkid -s UUID -o value /dev/sdb)  /mnt/disk1  ext4  defaults  0  0" >> /etc/fstab
      echo "UUID=$(blkid -s UUID -o value /dev/sdc)  /mnt/disk2  ext4  defaults  0  0" >> /etc/fstab
    SHELL
  end
end
