all:
  hosts:
    ansible-vm:
      ansible_host: 158.160.61.65
      ansible_user: yc-user
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
